name: publish
env:
  CI: true
on:
  push:
    branches:
      - main
    tags:
      - '!*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0
      - uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
        with:
          node-version: '20'
          cache: 'pnpm'
          always-auth: true
          registry-url: https://npm.pkg.github.com
          scope: '@hatena'
      - run: pnpm install --frozen-lockfile
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # まだ publish されていないバージョンなら publish する
      - name: publish package
        run: |
          npx can-npm-publish --verbose && pnpm publish || echo "Does not publish"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # package.json からバージョンを取得する
      - name: get version from package.json
        id: package-version
        run: echo "version=$(cat package.json | jq -r .version)" >> $GITHUB_OUTPUT
      # まだ tag がないバージョンなら tag を push する
      - name: publish tag
        uses: pkgdeps/git-tag-action@ef111413f44ebe5cc05994e7f5b5b9edaaada08d # v3.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          github_repo: ${{ github.repository }}
          git_commit_sha: ${{ github.sha }}
          version: ${{ steps.package-version.outputs.version }}
          git_tag_prefix: 'v'
