name: publish
env:
  CI: true
on:
  push:
    branches:
      - main
    tags:
      - '!*'

jobs:
  release:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup Node
        uses: actions/setup-node@v3
        with:
          always-auth: true
          node-version: 18.x
          registry-url: https://npm.pkg.github.com
          scope: '@hatena'

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v4
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.OS }}-yarn-

      - name: yarn install --frozen-lockfile
        run: yarn install --frozen-lockfile
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: yarn run lint
        run: yarn run lint

      # まだ publish されていないバージョンなら publish する
      - run: |
          npx can-npm-publish --verbose && npm publish || echo "Does not publish"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # package.json からバージョンを取得する
      - name: package-version
        id: package-version
        run: echo "version=$(cat package.json | jq -r .version)" >> $GITHUB_OUTPUT

      # まだ tag がないバージョンなら tag を push する
      - name: package-version-to-git-tag
        uses: pkgdeps/git-tag-action@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          github_repo: ${{ github.repository }}
          git_commit_sha: ${{ github.sha }}
          version: ${{ steps.package-version.outputs.version }}
          git_tag_prefix: 'v'
